PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>

INSERT DATA{
  GRAPH <$studyUri> {
    instance:$newUUID
      ontology:of_outcome <$outcomeUri> ;
      ontology:of_arm <$armUri> ;
      ontology:of_moment <$momentUri> ;
      ontology:sample_size $sampleSize ;
      ontology:mean $mean ;
      ontology:standard_deviation $stdDev .
  }
}
