PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX instance: <http://trials.drugis.org/instances/>

INSERT {
  $lastItem rdf:rest [
    rdf:first instance:$elementToInsert ;
    rdf:rest rdf:nil
  ]
} 
