PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
  ?x ontology:has_epochs ?list
}
INSERT {
  ?x ontology:has_epochs [ rdf:first '1234-abcd' ; rdf:rest ?list]
}
WHERE {
  ?study ontology:has_epochs ?list .
  ?x ontology:has_epochs ?list
}