PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT DATA {
  GRAPH <$graphUri> {
    <$activityUri> ontology:has_drug_treatment <$treatmentUri> .
    <$treatmentUnitUri>
      rdfs:label '$treatmentUnitLabel' ;
      a ontology:Unit .
    <$treatmentDrugUri>
      rdfs:label '$treatmentDrugLabel' ;
      a ontology:Drug .
    <$treatmentUri>
      rdf:type <$treatmentDoseType> ;
      ontology:treatment_has_drug <$treatmentDrugUri> ;
      rdf:type ontology:FixedDoseDrugTreatment ;
      ontology:treatment_dose [
        rdf:value $treatmentFixedValue ;
        ontology:units <$treatmentUnitUri> ;
        ontology:dosingPeriodicity "$treatmentDosingPeriodicity"^^xsd:duration
      ]
  }
}
