PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  GRAPH <$graphUri> {
    instance:$newItemUuid
      rdfs:label "$newLabel" ;
      ontology:relative_to_epoch <$epochUri> ;
      ontology:relative_to_anchor $anchorMoment ;
      ontology:time_offset "$timeOffset"^^xsd:duration .
  }
};
