PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  ?s ontology:has_number_of_centers ?numberOfCenters .
} WHERE {
  ?s ontology:has_number_of_centers ?numberOfCenters .
};

INSERT {
  GRAPH <$graphUri> {
    ?study ontology:has_number_of_centers $numberOfCenters .
  }
} WHERE {
  GRAPH <$graphUri> {
    ?study a ontology:Study .
  }
}


