PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  <$URI>
   rdfs:label ?label ;
}
INSERT {
  <$URI>
    rdfs:label "$newLabel" ;
}
WHERE {
  <$URI>
   rdfs:label ?label ;
}
