PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

WITH <$graphUri>
DELETE {
  <$armURI> rdfs:label ?label .
  <$armURI> rdfs:comment ?comment .
}
INSERT {
  <$armURI> rdfs:label "$newArmLabel" .
}
WHERE {
  <$armURI> rdfs:label ?label .
  <$armURI> rdfs:comment ?comment .
}
