PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX study: <http://trials.drugis.org/studies/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

## edit label and duration
WITH <$graphUri>
DELETE {
  <$URI>
   rdfs:label ?label ;
   ontology:duration ?oldDuration .
}
INSERT {
  <$URI>
    rdfs:label "$newLabel" ;
    ontology:duration "$newDuration"^^xsd:duration .
}
WHERE {
  <$URI>
   rdfs:label ?label ;
   ontology:duration ?oldDuration .
};

## edit comment (optional)
WITH <$graphUri>
DELETE {
  <$URI> rdfs:comment ?oldComment .
}
WHERE {
  <$URI> rdfs:comment ?oldComment .
};

WITH <$graphUri>
INSERT {
  <$URI> rdfs:comment "$newComment" .
}
WHERE {
	FILTER("" != "$newComment")
};


