PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontology: <http://trials.drugis.org/ontology#>

DELETE {
  GRAPH <$graphUri> {
    <$URI> ontology:is_measured_at ?measurementMoment .
  }
}
WHERE {
  GRAPH <$graphUri> {
    <$URI> ontology:is_measured_at ?measurementMoment
  }
};

WITH <$graphUri>
DELETE {
  <$URI>
    rdfs:label ?label ;
    ontology:of_variable ?variable .
  ?variable ontology:measurementType ?measurementType .
}
INSERT {
  <$URI>
    rdfs:label "$newLabel" ;
    ontology:of_variable [ ontology:measurementType <$newMeasurementType> ].
    $insertMeasurementMomentBlock
}
WHERE {
  <$URI>
    rdfs:label ?label ;
    ontology:of_variable ?variable .
  ?variable ontology:measurementType ?measurementType .
}
