PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?lastEpoch WHERE {
  ?study ontology:has_epochs ?list .
  ?list rdf:rest* ?last .
  ?last rdf:rest rdf:nil .
  ?last rdf:first ?lastEpoch
}
