prefix ontology: <http://trials.drugis.org/ontology#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select
?uri ?label ?measurementType
where {
  graph <$graphUri> {
   ?uri rdfs:label ?label ;
   ontology:of_variable [ ontology:measurementType ?measurementType ] ;
   rdf:type ontology:PopulationCharacteristic .
 }
}
