PREFIX ontology: <http://trials.drugis.org/ontology#>

SELECT * WHERE {
  GRAPH <$graphUri> {
    OPTIONAL { ?s ontology:has_allocation ?groupAllocationUri } .
    OPTIONAL { ?s ontology:has_blinding ?blindingUri } .
    OPTIONAL { ?s ontology:status ?statusUri } .
    OPTIONAL { ?s ontology:has_number_of_centers ?numberOfCenters } .
  }
}
