PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX dataset: <http://trials.drugis.org/datasets/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT
  ?unitName
WHERE {
  GRAPH ?graphUri {
    ?study ontology:has_activity ?treatmentActivity .

    ?treatmentActivity
      a ontology:TreatmentActivity ;
      ontology:has_drug_treatment [
        ontology:treatment_dose [
          ontology:unit ?unit
        ]
      ] .
    ?unit rdfs:label ?unitName .
  }
}
