PREFIX ontology: <http://trials.drugis.org/ontology#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?uri ?label ?epochUri ?epochLabel ?relativeToAnchor ?offset ?outcome ?outcomeLabel WHERE {
  GRAPH <$graphUri> {
    ?uri rdfs:label ?label .
    OPTIONAL {
      ?uri ontology:relative_to_epoch ?epochUri .
      ?epochUri rdfs:label ?epochLabel .
    }
    OPTIONAL {
      ?uri ontology:relative_to_anchor ?relativeToAnchor .
    }
    OPTIONAL {
      ?uri ontology:time_offset ?offset .
    }
    OPTIONAL {
      ?outcome
        ontology:is_measured_at_moment ?uri ;
        rdfs:label ?outcomeLabel .
    }
  }
}
