prefix ontology: <http://trials.drugis.org/ontology#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?uri ?label ?comment ?duration {
 ?uri rdfs:label ?label ;
      rdf:type ontology:Epoch .
 OPTIONAL { ?uri rdfs:comment ?comment .}
 OPTIONAL { ?uri ontology:duration ?duration .}
}