PREFIX owl: <http://www.w3.org/2002/07/owl#> 

WITH <$graphUri>
DELETE {
  <$studyConcept> owl:sameAs ?oldDatasetConcept .
} WHERE {
  <$studyConcept> owl:sameAs ?oldDatasetConcept .
};

INSERT DATA {  
  GRAPH <$graphUri> {
    <$studyConcept> owl:sameAs <$newDatasetConcept> .
  }
}


