PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX instance: <http://trials.drugis.org/instances/>

WITH <$graphUri>
INSERT {
  <$studyUri> ontology:has_primary_epoch instance:$newUUID
}
DELETE {
  ?study ontology:has_primary_epoch ?oldPrimary .
}
WHERE {
  OPTIONAL { ?study ontology:has_primary_epoch ?oldPrimary .}
}
