PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX study:	 <http://trials.drugis.org/studies/>

WITH <$graphUri>
DELETE {
  ?study ontology:has_primary_epoch ?oldPrimary .
}
INSERT {
  study:$studyUUID ontology:has_primary_epoch instance:$newUUID
}
WHERE {
  OPTIONAL { ?study ontology:has_primary_epoch ?oldPrimary .}
}
