PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  <$URI>  ontology:has_result_property ?oldProperty .
}
WHERE {
  <$URI>  ontology:has_result_property ?oldProperty .
};

WITH <$graphUri>
INSERT {
  <$URI>
     ontology:has_result_property ontology:count ;
     ontology:has_result_property ontology:sample_size .
}
WHERE {
  <$URI> ontology:measurementType <http://trials.drugis.org/ontology#dichotomous>
};

WITH <$graphUri>
INSERT {
  <$URI>
     ontology:has_result_property ontology:mean ;
     ontology:has_result_property ontology:standard_deviation ;
     ontology:has_result_property ontology:sample_size .
}
WHERE {
  <$URI> ontology:measurementType <http://trials.drugis.org/ontology#continuous>
};




