apiVersion: v1
kind: Pod
metadata:
  name: addis-db-init
  namespace: drugis-test
  labels:
    app: addis-db-init
spec:
  initContainers:
    - name: wait-for-db
      image: postgres:10.8
      env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
      command: ['sh', '-c']
      args:
        - until psql -h postgres -c  "select version();"; do echo waiting for postgres; sleep 2; done;
    - name: create-addis-user
      image: postgres:10.8
      env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: ADDIS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: addis-secrets
              key: ADDIS_DB_PASSWORD
      command: ['sh', '-c']
      args:
        - psql -h postgres -c  "DO \$\$ BEGIN CREATE ROLE addis LOGIN PASSWORD '$(ADDIS_DB_PASSWORD)'; EXCEPTION WHEN DUPLICATE_OBJECT THEN RAISE NOTICE 'not creating role addis -- it already exists'; END \$\$"
    - name: create-addis-database
      image: postgres:10.8
      env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD

      command: ['sh', '-c']
      args:
        - psql -h postgres -c "SELECT 1 FROM pg_database WHERE datname = 'addis'" | grep -q 1 || psql -h postgres -c "CREATE DATABASE addis"
  containers:
    - name: addis-liquibase
      image: addis/addis-liquibase
      env:
        - name: LIQUIBASE_URL
          value: 'jdbc:postgresql://postgres:5432/addis'
        - name: LIQUIBASE_USERNAME
          value: 'addis'
        - name: LIQUIBASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: addis-secrets
              key: ADDIS_DB_PASSWORD
        - name: LIQUIBASE_CHANGELOG
          value: 'liquibase-changelog.sql'
      args:
        - 'update'
  restartPolicy: Never
