PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  ?s ?p ?o .
  ?o ?p2 ?o2 .
  ?study ontology:has_outcome <$URI> .
}
WHERE {
  <$URI> ontology:of_variable? ?s.
  ?s ?p ?o .
  ?o ?p2 ?o2 .
  ?study ontology:has_outcome <$URI> .
};
