PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

WITH <$graphUri>
DELETE {
  ?s ontology:has_objective ?objectiveNode .
  ?objectiveNode rdfs:comment ?objective .
} WHERE {
  ?s ontology:has_objective ?objectiveNode .
  ?objectiveNode rdfs:comment ?objective .
};
