PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  <$indicationUri> rdfs:label ?oldLabel .
  ?s ontology:has_eligibility_criteria ?criteriaNode .
  ?criteriaNode rdfs:comment ?comment .
} WHERE {
  <$indicationUri> rdfs:label ?oldLabel .
  ?s ontology:has_eligibility_criteria ?criteriaNode .
  ?criteriaNode rdfs:comment ?comment .
};

INSERT {
  GRAPH <$graphUri> {
    <$indicationUri>
      a ontology:Indication ;
      rdfs:label "$indicationLabel" .
    ?study ontology:has_eligibility_criteria [
      rdfs:comment "$eligibilityCriteria"
    ]
  }
} WHERE {
  GRAPH <$graphUri> {
    ?study a ontology:Study .
  }
}


