PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  ?s ontology:has_allocation ?groupAllocationUri .
} WHERE {
  ?s ontology:has_allocation ?groupAllocationUri .
};

INSERT {
  GRAPH <$graphUri> {
    ?study ontology:has_allocation <$groupAllocationUri> .
  }
} WHERE {
  GRAPH <$graphUri> {
    ?study a ontology:Study .
  }
}


