PREFIX ontology: <http://trials.drugis.org/ontology#>

SELECT * WHERE {
  GRAPH <$graphUri> {
    ?s ontology:has_activity ?activityUri .
    ?activityUri ontology:has_activity_application [
      ontology:applied_to_arm ?armUri ;
      ontology:applied_in_epoch ?epochUri
    ] .
  }
}