PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT
?uri ?label ?measurementType ?conceptMapping
WHERE {
  GRAPH <$graphUri> {
    ?uri
      rdfs:label ?label ;
      ontology:of_variable [
        ontology:measurementType ?measurementType
      ] ;
    rdf:type ontology:Endpoint .
    OPTIONAL {
      ?uri ontology:of_variable [
        owl:sameAs ?conceptMapping
      ]
    }
  }
}
