PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
 ?activity ontology:has_activity_application ?application .
  ?application 
    ontology:applied_in_epoch <$epochUri> ;
    ontology:applied_to_arm <$armUri> .
}
WHERE {
  ?activity ontology:has_activity_application ?application .
  ?application 
    ontology:applied_in_epoch <$epochUri> ;
    ontology:applied_to_arm <$armUri> .
};

INSERT DATA {
  GRAPH <$graphUri> {
    <$activityUri> ontology:has_activity_application [
      ontology:applied_in_epoch <$epochUri> ;
      ontology:applied_to_arm <$armUri> ;
    ] ;
  }
} 