PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
  ?blankNode owl:sameAs ?oldDatasetConcept
} WHERE {
  <$studyConcept> ontology:of_variable ?blankNode .
  ?blankNode owl:sameAs ?oldDatasetConcept
};

WITH <$graphUri>
INSERT {
  ?blank owl:sameAs <$datasetConcept> .
} WHERE {
  <$studyConcept> ontology:of_variable ?blank .
}


