PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
  graph <$graphUri> {
    ?study ontology:has_outcome instance:$UUID .
    instance:$UUID
    rdfs:label "$label" ;
    ontology:of_variable [ ontology:measurementType <$measurementType> ] ;
    a ontology:PopulationCharacteristic .
  }
} WHERE {
  graph <$graphUri> {
    ?study a ontology:Study
  }
}
