PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>

INSERT DATA {
  GRAPH <$graphUri> {
    <$resultUri>
      ontology:of_outcome <$outcomeUri> ;
      ontology:of_arm <$armUri> ;
      ontology:of_moment <$momentUri> ;
      ontology:$valueType $actualValue .
    }
}
