PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>

SELECT * WHERE {
  GRAPH <$graphUri> {
    ?instance
      ontology:of_outcome <$outcomeUri> ;
      ontology:of_arm ?armUri ;
      ontology:of_moment ?momentUri ;
      ?result_property ?value .
      <$outcomeUri> ontology:has_result_property ?result_property .
  }
}