PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX ontology: <http://trials.drugis.org/ontology#>

WITH <$graphUri>
DELETE {
    <$resultUri>
      ontology:$valueType ?value .
}
INSERT {
    <$resultUri>
      ontology:of_outcome <$outcomeUri> ;
      ontology:of_arm <$armUri> ;
      ontology:of_moment <$momentUri> ;
      ontology:$valueType $actualValue .
}
WHERE {
    OPTIONAL { <$resultUri> ontology:$valueType ?value }.
}
