PREFIX dataset: <http://trials.drugis.org/datasets/>
PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE {
  ?dataset dcterms:title ?title
} WHERE {
  ?dataset dcterms:title ?title
};
INSERT DATA {
  <$datasetUri> dcterms:title "$newTitle"
};
DELETE {
  <$datasetUri> dcterms:description ?description
} WHERE {
  <$datasetUri> dcterms:description ?description
};
