PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX dataset: <http://trials.drugis.org/datasets/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX graph: <http://trials.drugis.org/graphs/>

SELECT ?intervention ?label WHERE {
GRAPH graph:concepts {
      ?intervention a ontology:Drug ;
      rdfs:label ?label .
  }
}
