PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ontology: <http://trials.drugis.org/ontology#>

## ADD sourceUrl

SELECT ?dataset ?label ?comment (COUNT(?study) AS ?numberOfStudies) WHERE {
  ?dataset dcterms:title ?label .
  OPTIONAL { ?dataset dcterms:description ?comment . } .
  OPTIONAL {
    graph ?study {
      ?studyUri a ontology:Study .
    }
  }
} GROUP BY ?dataset ?label ?comment

