PREFIX dataset: <http://trials.drugis.org/datasets/>
PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE {
  ?dataset dcterms:archived ?archived
} WHERE {
  ?dataset dcterms:archived ?archived
};
DELETE {
  ?dataset dcterms:archivedOn ?archivedOn
} WHERE {
  ?dataset dcterms:archivedOn ?archivedOn
};
INSERT DATA {
  <$datasetUri> dcterms:archived "$newArchived"
};
INSERT DATA {
  <$datasetUri> dcterms:archivedOn "$archivedOn"
};

