PREFIX dataset: <http://trials.drugis.org/datasets/>
PREFIX ontology: <http://trials.drugis.org/ontology/>

DELETE {
  ?dataset ontology:archived ?archived
} WHERE {
  ?dataset ontology:archived ?archived
};
DELETE {
  ?dataset ontology:archivedOn ?archivedOn
} WHERE {
  ?dataset ontology:archivedOn ?archivedOn
};
INSERT DATA {
  <$datasetUri> ontology:archived "$newArchived"
};
INSERT DATA {
  <$datasetUri> ontology:archivedOn "$archivedOn"
};
