# All SNOMED CT top-level disease terms
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX snomed: <http://www.ihtsdo.org/>

SELECT * WHERE {
  GRAPH <http://www.ihtsdo.org/SNOMEDCT/> {
    ?uri rdfs:subClassOf snomed:SCT_64572001 .
    ?uri rdfs:label ?label .
  }
}
