# Broader SNOMED disease terms
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX snomed: <http://www.ihtsdo.org/>
PREFIX atc: <http://www.whocc.no/ATC2011/>

SELECT * WHERE {
  <%= restrict.graphQuery %>
  GRAPH <%= restrict.graph %> {
    <<%= uri %>> rdfs:subClassOf ?uri .
    ?uri rdfs:label ?label .
    <%= restrict.sparql %>
  }
} LIMIT 10
