PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX instance: <http://trials.drugis.org/instances/>
PREFIX graph: <http://trials.drugis.org/graphs/>

SELECT DISTINCT
?graph
?value
WHERE {
  GRAPH ?graph {
    ?study a ontology:Study .
    OPTIONAL {
      ?study ontology:has_allocation ?X .
      BIND ( IF (?X = ontology:AllocationRandomized, 1, 0)  AS ?value )
    }
  }
}