PREFIX ontology: <http://trials.drugis.org/ontology#>
PREFIX dataset: <http://trials.drugis.org/datasets/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX graph: <http://trials.drugis.org/graphs/>
PREFIX list: <http://jena.hpl.hp.com/ARQ/list#>
PREFIX instance: <http://trials.drugis.org/instances/>

SELECT ?armUid ?armLabel ?numberOfParticipantsStarting {
   GRAPH graph:$studyUid {
       ?study ontology:has_arm ?armUid .
       ?armUid a ontology:Arm ;
         rdfs:label ?armLabel .
       OPTIONAL {
         ?participantFlow a ontology:ParticipantFlow ;
             ontology:participants_starting ?numberOfParticipantsStarting ;
             ontology:of_arm ?armUid .
       }
   }
 }