prefix dc: <http://purl.org/dc/elements/1.1/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dataset: <http://trials.drugis.org/datasets/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ontology: <http://trials.drugis.org/ontology#>

CONSTRUCT {
    ?dataset rdf:type ontology:Dataset ;
      rdfs:label ?title;
      rdfs:comment ?description;
      dc:creator $owner .
}
WHERE {
  GRAPH ?dataset {
    ?dataset rdf:type ontology:Dataset ;
      rdfs:label ?title ;
      dc:creator $owner .
      OPTIONAL {
        ?dataset rdfs:comment ?description .
      } .
  }
}

